apiVersion: apps/v1
kind: Deployment
metadata:
  name: as-deployment
  labels:
    app: as
spec:
  replicas: 1
  selector:
    matchLabels:
      app: as
  template:
    metadata:
      labels:
        app: as
    spec:
      containers:
        - name: as-container
          image: ethanliu393/as:latest
          ports:
            - containerPort: 53533
              protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: as-service
spec:
  type: NodePort
  selector:
    app: as
  ports:
    - port: 53533
      targetPort: 53533
      nodePort: 30001
      protocol: UDP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fs-deployment
  labels:
    app: fs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fs
  template:
    metadata:
      labels:
        app: fs
    spec:
      containers:
        - name: fs-container
          image: ethanliu393/fs:latest
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: fs-service
spec:
  type: NodePort
  selector:
    app: fs
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: us-deployment
  labels:
    app: us
spec:
  replicas: 1
  selector:
    matchLabels:
      app: us
  template:
    metadata:
      labels:
        app: us
    spec:
      containers:
        - name: us-container
          image: ethanliu393/us:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: us-service
spec:
  type: NodePort
  selector:
    app: us
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30003
